name: Seed DB

on:
  schedule:
    - cron:  '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Install faker python dependency
    - name: Install Faker
      run: pip3 install faker

    # Install firebase dependency
    - name: Install firebase-admin
      run: npm i firebase-admin

    # Runs a set of commands using the runners shell
    - name: Create Dataset and update firebase
      run: |
        python3 ./scheme/data.py
        cat ./data.json
        npm ls firebase-admin