# This is a basic workflow to help you get started with Actions

name: Seed DB

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron:  '* * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Install faker python dependency
    - name: Install Faker
      run: pip3 install faker

    # Install firebase dependency
    - name: Install firebase-admin
      run: npm i firebase-admin

    # Runs a set of commands using the runners shell
    - name: Create Dataset and update firebase
      run: |
        python3 ./scheme/data.py
        cat ./data.json
        npm ls firebase-admin
     # (uncomment this to run the upload script) node ./scheme/uploadMock.js